@startuml
class com.example.platform_for_volunteer_projects.MainController {
- CurrentUser currentUser
- Event selectedEvent
- Event selectedMeeting
- ObservableList<Event> eventList
- TableView<Event> tableViewRecords
- TableColumn<Event,String> nameColumn
- TableColumn<Event,String> descriptionColumn
- TableColumn<Event,String> locationColumn
- TableColumn<Event,Integer> maxPeopleColumn
- Button buttonRecordsMeets
- Button buttonLogout
- TableView<Event> tableViewMeetings
- TableColumn<Event,String> meetingNameColumn
- TableColumn<Event,String> meetingDateColumn
- TableColumn<Event,String> meetingTimeColumn
- TableColumn<Event,String> meetingStatusColumn
+ void initialize()
+ void initUserData(CurrentUser)
- void initializeMeetingsTable()
- void initializeRecordsTable()
- void loadEventsFromDatabase()
- void handleLogout()
- void handleGenerateCertificate()
- void createWordCertificate(String,String,String,String)
- String generateCertificateNumber()
- void registerForEvent()
- void sendEmail(String,String,String)
- void showAlert(String,String)
}


@enduml