@startuml
class com.example.platform_for_volunteer_projects.ObserverController {
- TableView<Event> tableViewNews
- TableColumn<Event,String> colName
- TableColumn<Event,String> colDate
- Button buttonLogout
+ void initialize()
- void loadEventsFromDatabase()
- void handleLogout()
- void showAlert(String,String,String)
}


class com.example.platform_for_volunteer_projects.ObserverController$Event {
- String name
- String date
+ String getName()
+ String getDate()
}




com.example.platform_for_volunteer_projects.ObserverController +.. com.example.platform_for_volunteer_projects.ObserverController$Event
@enduml